FROM almalinux:9
ADD https://raw.githubusercontent.com/ImManiKanta/dockerfiles/refs/heads/main/1.FROM/Dockerfile /tmp/ #Download the content and place it in destination
ADD sample.tar /tmp/  #untar the file in destination